FROM python:3.10-slim

WORKDIR /app

# Installer les dépendances nécessaires directement
RUN pip install --no-cache-dir streamlit pandas pyarrow

COPY app/ .

CMD ["streamlit", "run", "streamlit_dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]